### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by kopitek8** [collective-service/ifrc-gates-dashboard#271]
## Issues Within This Epic

- [x] #120 - invalid
- [ ] #152 - Consult with Ankit
- [x] #296 

## UAT Changes Within This Epic

- [x] #237 
- [x] #247 - invalid - confirm this with not removing indicators when clearing out a region because it might be redundant work (hierarchy issues)

## Version 2 Changes Within This Epic

- [x] #244 
- [x] #250 
- [ ] #239 - clarify more w/ Julien before starting work
- [ ] #251 

#### To do from assigned personnel

_**Open the issue, self-assign the issue (and remove others), track the issue via 'Status' on the right side, and tick the issue here after completion**_
